is_debug: true

listen:
  type: https
  bind_ip: 0.0.0.0
  port: "8080"


provider_historical:
  network_name: "ethereum"
  base_url: "https://eth-mainnet.g.alchemy.com/v2/"
  compute_units_per_second: 500
  compute_units_per_10seconds: 5000
  request_per_second: 25
  max_retries: 5
  api_keys:
    - ""
    - ""

provider_realtime: 
  provider_type: "alchemy" 
  network_name: "ethereum"
  base_url: "wss://eth-mainnet.g.alchemy.com/v2/" 
  api_key: "Uzb0sDJmjCuvs21_OyLbn"
  limiter: 25
  max_retries: 5

broker:
  brocker_type: "mock"
