root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "cd .. && go work sync && cd - && go build -o ./tmp/main ./cmd/main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  include_ext = ["go", "toml", "yaml", "yml", "json"]
  kill_delay = "1s"

[log]
  time = false

[misc]
  clean_on_exit = true