FROM golang:1.25-alpine

# Устанавливаем air для hot reload
RUN go install github.com/cosmtrek/air@latest

# Создаем рабочую директорию
WORKDIR /workspace

# Копируем корневые go модули для кэширования
COPY lib/go.mod lib/go.sum ./
RUN go mod download

# Устанавливаем зависимости для разработки
RUN apk add --no-cache git